name: Perl Critic

on:
  push:
    branches:
      - master
      - hangy-patch-1
      - harsh-critic-annotated
      - harsh-critic
  pull_request:
    branches:
      - master
      - hangy-patch-1
      - harsh-critic-annotated
      - harsh-critic

jobs:
  perlcritic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Perl Critic
      uses: hangy/action-perlcritic@04fb01c0290120cdc56cd5e071c4615e98bb5d10
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: cgi/*.pl scripts/*.pl lib/ProductOpener/*.pm lib/*.pl t/*.t
