name: Perl Critic

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  perlcritic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Perl Critic
      uses: hangy/action-perlcritic@e40ccc13ae40df6c4b3d2e25fdcbfab4b5bbaccd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: cgi/*.pl scripts/*.pl lib/ProductOpener/*.pm lib/*.pl t/*.t
